name: Launch keycloak
description: Checkout keycloak module for installation and to launch keycloak docker

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      name: Checkout keycloak module
      with:
        repository: PrestaShop/keycloak_connector_demo
        ref: v1.1.0
        path: keycloak_connector_demo
    - name: Build keycloak docker and install module via CLI command
      run: |
        USER_ID=$(id -u) GROUP_ID=$(id -g) docker compose -f keycloak_connector_demo/docker-compose-ui.yml up -d
      shell: bash
